export const collection = [
	{
		title: "Banking Isometric 3d Vectors Collection",
		length: 201,
		svg: [
			"banks/provident-fund-inquiry-svgrepo-com.svg",
			"banks/check-in-svgrepo-com.svg",
			"banks/credit-report-svgrepo-com.svg",
			"banks/currency-exchange-svgrepo-com.svg",
			"banks/deposit-svgrepo-com.svg",
			"banks/financial-security-svgrepo-com.svg",
			"banks/help-svgrepo-com.svg",
			"banks/loan-svgrepo-com.svg",
		],
	},
	{
		title: "Medical Duotone Line Icons Collection",
		length: 201,
		svg: [
			"medicine/infusion-svgrepo-com.svg",
			"medicine/electrocardiogram-svgrepo-com.svg",
			"medicine/ambulance-svgrepo-com.svg",
			"medicine/doctor-svgrepo-com.svg",
			"medicine/clinic-building-svgrepo-com.svg",
			"medicine/capsule-svgrepo-com.svg",
			"medicine/beaker-svgrepo-com.svg",
			"medicine/ambulance-svgrepo-com.svg",
		],
	},

	{
		title: "Internet Duotone Line Icons Collection",
		length: 201,
		svg: [
			"Internet/7x24h-svgrepo-com.svg",
			"Internet/all-covered-svgrepo-com.svg",
			"Internet/api-interface-svgrepo-com.svg",
			"Internet/availability-svgrepo-com.svg",
			"Internet/cloud-acceleration-svgrepo-com.svg",
			"Internet/cloud-backup-svgrepo-com.svg",
			"Internet/data-analysis-svgrepo-com.svg",
			"Internet/ddos-protection-svgrepo-com.svg",
		],
	},
	{
		title: "Biological Gene Duotone Icons Collection",
		length: 201,
		svg: [
			"genetic-engineering-svgrepo-com.svg",
			"bacteria-svgrepo-com.svg",
			"gene-sequencing-svgrepo-com.svg",
			"genetically-modified-svgrepo-com.svg",
			"microorganism-svgrepo-com.svg",
			"organic-organism-svgrepo-com.svg",
			"supercoil-svgrepo-com.svg",
			"nucleus-svgrepo-com.svg",
		],
	},
	{
		title: "Travel Industry Icons Collection",
		length: 201,
		svg: [
			"building-svgrepo-com.svg",
			"diving-goggles-svgrepo-com.svg",
			"hat-svgrepo-com.svg",
			"high-speed-rail-svgrepo-com.svg",
			"hotel-svgrepo-com.svg",
			"medicine-bottle-svgrepo-com.svg",
			"passport-svgrepo-com.svg",
			"suitcase-svgrepo-com.svg",
		],
	},
	{
		title: "Daily Life Vectors Collection",
		length: 201,
		svg: [
			"life/alarm-clock-svgrepo-com.svg",
			"life/bedside-table-svgrepo-com.svg",
			"life/brush-svgrepo-com.svg",
			"life/camera-svgrepo-com.svg",
			"life/chip-svgrepo-com.svg",
			"life/desk-lamp-svgrepo-com.svg",
			"life/earphone-svgrepo-com.svg",
			"life/fan-svgrepo-com.svg",
		],
	},
	{
		title: "Business Duotone Tiny Icons Collection",
		length: 201,
		svg: [
			"business/article-svgrepo-com.svg",
			"business/badge-svgrepo-com.svg",
			"business/broadcast-svgrepo-com.svg",
			"business/camera-svgrepo-com.svg",
			"business/card-holder-svgrepo-com.svg",
			"business/cell-phone-svgrepo-com.svg",
			"business/coffee-svgrepo-com.svg",
			"business/collect-svgrepo-com.svg",
		],
	},

];
export const buttons = [
	{ title: "All Styles", href: "", svg: "" },
	{ title: "Monocolor", href: "", svg: "monocolor.svg" },
	{ title: "Multicolor", href: "", svg: "multicolor.svg" },
	{ title: "Duotone", href: "", svg: "duotone.svg" },
	{ title: "Outlined", href: "", svg: "outlined.svg" },
	{ title: "Filled", href: "", svg: "filled.svg" },
	{ title: "Icon", href: "", svg: "icon.svg" },
	{ title: "Glyph", href: "", svg: "glyph.svg" },
	{ title: "Rounded", href: "", svg: "rounded.svg" },
	{ title: "Sharp", href: "", svg: "sharp.svg" },
];
export const buttonsCollection = [
	{ title: "Monocolor", href: "", svg: "monocolor.svg" },
	{ title: "Multicolor", href: "", svg: "multicolor.svg" },
	{ title: "Outlined", href: "", svg: "outlined.svg" },
	{ title: "Filled", href: "", svg: "filled.svg" },
	{ title: "Icon", href: "", svg: "icon.svg" },
	{ title: "Glyph", href: "", svg: "glyph.svg" },
	{ title: "Interface", href: "", svg: "interface.svg" },

	{ title: "Duotone", href: "", svg: "duotone.svg" },
	{ title: "Flat", href: "", svg: "flat.svg" },
	{ title: "Bordered", href: "", svg: "bordered.svg" },
	{ title: "Tritone", href: "", svg: "tritone.svg" },
	{ title: "Line", href: "", svg: "line.svg" },

	{ title: "Bold", href: "", svg: "bold.svg" },
	{ title: "Thin", href: "", svg: "thin.svg" },
	{ title: "Dashed", href: "", svg: "dashed.svg" },
	{ title: "Tiny", href: "", svg: "tiny.svg" },
	{ title: "Basic", href: "", svg: "basic.svg" },
	{ title: "Sharp", href: "", svg: "sharp.svg" },
	{ title: "Rounded", href: "", svg: "rounded.svg" },
	{ title: "Circular", href: "", svg: "circular.svg" },
	{ title: "Set", href: "", svg: "set.svg" },
	{ title: "Emoji", href: "", svg: "emoji.svg" },
	{ title: "Logo", href: "", svg: "logo.svg" },
	{ title: "Pixel", href: "", svg: "pixel.svg" },
	{ title: "Stylized", href: "", svg: "stylized.svg" },
	{ title: "Doodle", href: "", svg: "doodle.svg" },
	{ title: "Hand Drawn", href: "", svg: "hand-drawn.svg" },
	{ title: "Gradient", href: "", svg: "gradient.svg" },
	{ title: "Isometric", href: "", svg: "isometric.svg" },
	{ title: "Sticker", href: "", svg: "sticker.svg" },
	{ title: "3D", href: "", svg: "3d.svg" },
];
